### ISSUE TITLE
Templates don't obey project name/namespaces

### ISSUE THREAD

**Issue by tillig** [DuendeSoftware/IdentityServer.Templates#16]
When doing something like `dotnet new classlib --name My.Library.Here` the class library generated files (e.g., `Class1.cs`) will be in the namespace based on the project name you provided:

```c#
namespace My.Library.Here;
public class Class1
{
}
```

However, it appears the IdentityServer templates (at least, for things under`Pages`) don't have that feature - `dotnet new isinmem --name MyServer` will put the root items (e.g., `Config.cs`) in the right namespace, but the stuff under the `Pages` folder is all in the `IdentityServerHost` namespace.

```c#
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IdentityServerHost.Pages;

public class SecurityHeadersAttribute : ActionFilterAttribute
{
}
```

Is that intentional? It makes for some search-and-replace work after the template is stamped out. It'd be nice if everything obeyed the specified namespace.

**Comment by leastprivilege** [comment]
Thanks for reporting.

We are aware of this issue and know that it is not ideal.

The problem comes from the fact that the UI bits come from our main repo and get distributed into various places - including the templates. Renaming the namespaces every time would be a major complication.

Do you know if the .NET templating engine allows for supplying additional string transforms? This way the namespace could be potentially renamed at "dotnet new" time..

**Comment by tillig** [comment]
I tinkered with it a bit and I think adding a symbol to rename the common namespace will work:

```json
{
  "symbols": {
    "RenameCommonNamespace": {
      "datatype": "string",
      "displayName": "Common host namespace.",
      "replaces": "IdentityServerHost",
      "type": "derived",
      "valueSource": "name",
      "valueTransform": "safe_namespace"
    }
  }
}
```

Let me try it out and put a PR together if it works.

**Comment by tillig** [comment]
Added #22 for this.
